### ISSUE TITLE
SEVERTIY: 2 - TITLE: Multiple Spelling Errors

### ISSUE THREAD

**Issue by HavocHunter** [ctaetcsh/ctaetcsh.github.io#2]
ReadMe.md: Analytics is spelt wrong, you put 'Anyalitcs', when it is spelt 'analytics'

index.html: describe is spelt wrong, you spelt it "To discribe me shortly" when it should be "To describe me

/r/twtr.html: 
"  If you are not redirected automatically, <a href="https://https://twitter.com/ctaetcsh" >click here</a>" 
should be  
 "If you are not redirected automatically, <a href="https://twitter.com/ctaetcsh" >click here</a>"

Contact: 5HADOW#6620
Severity (1-10): 5

**Comment by ctaetcsh** [comment]
Redir pages all need to be updated

Severity moved from 5 to 2

**Comment by ctaetcsh** [comment]
Pull Request merged with master and issue closed.
